pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - label!=work-in-progress
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - base=master
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
